### ISSUE TITLE
Add linter, fix code style and package.json

### ISSUE THREAD

**Issue by tshemsedinov** [tedi4t/telegram_bot#1]
- [x] Add eslint config, you may use this one: https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.eslintrc.json
- [x] Add `package.json`
- [x] Add `README.md`
- [x] Add `LICENSE`

**Comment by tedi4t** [comment]
Have done everything. Thank you for your recommendations. I will be glad to hear any comments or remarks.
